Repository opensearch-project/notifications, pull requests merged in 2022-10, with the labels that each got.

#545 Add test case for LEGACY SNS and 2.4 version update
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
  dashboards-notifications/opensearch_dashboards.json
  dashboards-notifications/package.json
  notifications/build.gradle
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/send/SendMessageActionHelper.kt
Labels: backport 2.x

#546 Add test case for LEGACY SNS
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/send/SendMessageActionHelper.kt
Labels: backport 2.3

#549 add groupId to pluginzip publication
  notifications/core/build.gradle
Labels: backport 2.x, v2.4.0

#552 add groupId to pluginzip publication
  notifications/notifications/build.gradle
Labels: backport 2.x, v2.4.0

#554 Fix error `InvalidMavenPublicationException`
  notifications/settings.gradle
Labels: backport 2.x, v2.4.0
