Repository opensearch-project/notifications, pull requests merged in 2022-08, with the labels that each got.

#470 Add security tests and workflow plus minor fix
  .github/workflows/security-notifications-test-workflow.yml
  notifications/notifications/build.gradle
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/action/SendTestNotificationAction.kt
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/NotificationConfigIndex.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/AccessRoles.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/IntegTestHelpers.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/PluginRestTestCase.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/features/GetNotificationChannelListIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/send/SendTestMessageRestHandlerIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/notifications/ObjectEqualsHelpers.kt
Labels: backport 2.x

#496 Resolve hosts when checking against host deny list
  notifications/core-spi/build.gradle
  notifications/core-spi/src/main/kotlin/org/opensearch/notifications/spi/utils/ValidationHelpers.kt
  notifications/core-spi/src/test/kotlin/org/opensearch/notifications/spi/utils/ValidationHelpersTests.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/destinations/ChimeDestinationTests.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/destinations/CustomWebhookDestinationTests.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/destinations/SlackDestinationTests.kt
Labels: backport 2.0, backport 2.x, backport 2.1

#502 Add release notes for 2.2.0
  release-notes/opensearch-notifications.release-notes-2.2.0.0.md
Labels: backport 2.2

#478 Incremented version to 2.1.1.
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
  dashboards-notifications/opensearch_dashboards.json
  dashboards-notifications/package.json
  notifications/build.gradle
  notifications/core/build.gradle
  notifications/notifications/build.gradle
Labels: v2.1.1

#507 Disable following redirects for webhooks
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/client/DestinationHttpClient.kt
Labels: backport 2.0, backport 2.x, backport 2.1, backport 2.2

#513 Bump to 2.3.0
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
  .github/workflows/security-notifications-test-workflow.yml
  dashboards-notifications/opensearch_dashboards.json
  dashboards-notifications/package.json
  notifications/build.gradle
  notifications/core/build.gradle
  notifications/notifications/build.gradle
Labels: backport 2.x
