Repository opensearch-project/notifications, pull requests merged in 2022-04, with the labels that each got.

#404 Remove scripts from notifications repo due to naming of the entries in manifest file
  dashboards-notifications/scripts/build.sh
  notifications/scripts/build.sh
Labels: v2.0.0, release

#411 [Build] add common to tsconfig
  dashboards-notifications/.opensearch_dashboards-plugin-helpers.json
  dashboards-notifications/tsconfig.json
Labels: v2.0.0

#424 Rename settings and combine RBAC settings into one
  notifications/core/src/main/config/notifications-core.yml
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/setting/PluginSettings.kt
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/utils/ValidationHelpers.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/settings/PluginSettingsTests.kt
  notifications/notifications/src/main/config/notifications.yml
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/security/UserAccess.kt
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/security/UserAccessManager.kt
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/send/SendMessageActionHelper.kt
  notifications/notifications/src/main/kotlin/org/opensearch/notifications/settings/PluginSettings.kt
  notifications/notifications/src/test/kotlin/org/opensearch/notifications/settings/PluginSettingsTests.kt
Labels: backport 2.0

#431 Add release notes for 2.0.0.0-rc1
  DEVELOPER_GUIDE.md
  release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
Labels: backport 2.0

#436 Fix Cypress tests
  dashboards-notifications/.cypress/integration/channels.spec.js
  dashboards-notifications/.cypress/integration/dashboard.spec.js
  dashboards-notifications/.cypress/integration/email_senders_and_groups.spec.js
  dashboards-notifications/.cypress/support/commands.js
  dashboards-notifications/.cypress/support/constants.js
  dashboards-notifications/cypress.json
  dashboards-notifications/public/pages/CreateChannel/__tests__/__snapshots__/ChannelNamePanel.test.tsx.snap
  dashboards-notifications/public/pages/CreateChannel/components/ChannelNamePanel.tsx
Labels: backport 2.0
