Repository opensearch-project/notifications, pull requests merged in 2023-07, with the labels that each got.

#702 Add 2.9.0 release notes
  release-notes/opensearch-notifications.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#717 fix gradle run
  notifications/build-tools/merged-coverage.gradle
  notifications/build.gradle
  notifications/core-spi/build.gradle
  notifications/core/build.gradle
Labels: backport 2.x

#716 Support SNS FIFO queues
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/client/DestinationSnsClient.kt
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/setting/PluginSettings.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/settings/PluginSettingsTests.kt
Labels: backport 2.x, backport 2.3, backport 2.5, backport 2.9, backport 2.7

#732 Fix core XcontentFactory refactor
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/client/DestinationHttpClient.kt
Labels: v2.10.0
