Repository opensearch-project/notifications, pull requests merged in 2023-10, with the labels that each got.

#774 Add 2.11 release notes
  release-notes/opensearch-notifications.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#784 Fix integration test failure by allowing direct access to system index warning
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/PluginRestTestCase.kt
Labels: backport 2.x, backport 2.11

#796 Re-enable detekt
  notifications/build.gradle
Labels: backport 2.x

#792 Improve security plugin enabling check
  .github/workflows/security-notifications-test-workflow.yml
Labels: backport 2.x

#799 Add github workflow to auto bump bwc version
  .github/workflows/bump-bwc.yml
Labels: backport 2.x

#801 Replace the TestMailServer to GreenMail server
  notifications/core/build.gradle
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/smtp/SmtpEmailTests.kt
Labels: backport 2.x, HackoberFest2023
