Repository opensearch-project/notifications, pull requests merged in 2023-01, with the labels that each got.

#591 Remove Jackson databind and annotations
  notifications/core-spi/build.gradle
  notifications/core/build.gradle
  notifications/notifications/build.gradle
Labels: backport 2.x

#590 Add index refresh after config creation and deletion in integration tests
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/PluginRestTestCase.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/bwc/NotificationsBackwardsCompatibilityIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/ChimeNotificationConfigCrudIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/CreateNotificationConfigIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/DeleteNotificationConfigIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/EmailNotificationConfigCrudIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/QueryNotificationConfigIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/SlackNotificationConfigCrudIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/SnsNotificationConfigCrudIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/WebhookNotificationConfigCrudIT.kt
  notifications/notifications/src/test/kotlin/org/opensearch/integtest/send/SendTestMessageRestHandlerIT.kt
Labels: backport 2.0, backport 2.x, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#587 Add BWC tests for running against distribution bundle
  notifications/notifications/build.gradle
  notifications/notifications/src/test/resources/security/sample.pem
Labels: v2.5.0, backport 2.5

#600 add release notes for 2.5
  release-notes/opensearch-notifications.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5
