Repository opensearch-project/notifications, pull requests merged in 2024-02, with the labels that each got.

#849 Fix CVE-2023-6378 for notifications
  notifications/build.gradle
Labels: backport 2.x, backport 2.11

#858 adding hostname support for notifications deny list
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/utils/ValidationHelpers.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/utils/ValidationHelpersTests.kt
Labels: backport 2.x, backport 2.12

#861 Adding max http response string length as a setting, and capping http…
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/client/DestinationHttpClient.kt
  notifications/core/src/main/kotlin/org/opensearch/notifications/core/setting/PluginSettings.kt
  notifications/core/src/test/kotlin/org/opensearch/notifications/core/settings/PluginSettingsTests.kt
Labels: backport 2.x, backport 2.9, backport 2.7, backport 2.11, backport 2.12
